### ISSUE TITLE
Install QIIME2

### ISSUE THREAD

**Issue by fabianomenegidio** [florianbegusch/qiime2_wrappers#2]
How did you install QIIME2 to work with these wrappers on Galaxy? I am trying to do this local installation and cannot connect qiime2 with wrappers.

Thanks.

**Comment by diepfote** [comment]
The tool is available in Galaxy's Toolshed https://toolshed.g2.bx.psu.edu/view/florianbegusch/qiime2_suite/21c7954105a9.
Hope this helps.
Cheers

**Comment by diepfote** [comment]
If this is not an option for you, you can install qiime2 2019.7 manually using conda.
To have Galaxy regonize the installation the name has to match '__qiime2@\<VERSION\>':  
```$ conda env create --name __qiime2@2019.7 qiime2==2019.7 --file qiime2-2019.7-py36-linux-conda.yml```


I wrote a script some time ago (save as ```install_qiime2.sh```):
```
#!/usr/bin/env bash

set -x

full_version="$1"
env_version_suffix="$(echo "$1" | cut -d '-' -f1)"

download_yaml_file="$2"

conda update -y conda

if [ -z "$download_yaml_file" ]; then
  curl -LO "https://data.qiime2.org/distro/core/qiime2-$full_version-linux-conda.yml"
fi

# in case of a ResolvePackageNotFound error --> look at the labels on anaconda e.g. r-pillar 1.2.2: https://anaconda.org/conda-forge/r-pillar/files?version=1.2.2&channel=cf201901
#
# to install as a tool dependency manually:
# $ conda env create --name __qiime2@2019.4 qiime2==2019.4 --file qiime2-2019.4-py36-linux-conda.yml
#
conda env create -n qiime2-"$env_version_suffix" --file qiime2-"$full_version"-linux-conda.yml
```

Then run:
```
chmod +x install_qiime2.sh
./install_qiime2.sh 2019.7-py36
```
